//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursadarbs_reactiveUI.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kursadarbs_reactiveUI.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Moody Pal!.
        /// </summary>
        public static string AppGreeting {
            get {
                return ResourceManager.GetString("AppGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string AppTitleButton {
            get {
                return ResourceManager.GetString("AppTitleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Timer.
        /// </summary>
        public static string AppTitleButton1 {
            get {
                return ResourceManager.GetString("AppTitleButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To-Do List.
        /// </summary>
        public static string AppTitleButton2 {
            get {
                return ResourceManager.GetString("AppTitleButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        public static string AppTitleButton3 {
            get {
                return ResourceManager.GetString("AppTitleButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done. You can close this now.
        /// </summary>
        public static string BreatheDone {
            get {
                return ResourceManager.GetString("BreatheDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold it....
        /// </summary>
        public static string BreatheHold {
            get {
                return ResourceManager.GetString("BreatheHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhale....
        /// </summary>
        public static string BreatheIn {
            get {
                return ResourceManager.GetString("BreatheIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhale....
        /// </summary>
        public static string BreatheOut {
            get {
                return ResourceManager.GetString("BreatheOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try a different one.
        /// </summary>
        public static string BreathingAlternative {
            get {
                return ResourceManager.GetString("BreathingAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Breathing.
        /// </summary>
        public static string BreathingOption1 {
            get {
                return ResourceManager.GetString("BreathingOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-7-8 Breathing.
        /// </summary>
        public static string BreathingOption2 {
            get {
                return ResourceManager.GetString("BreathingOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Breathing.
        /// </summary>
        public static string BreathingOption3 {
            get {
                return ResourceManager.GetString("BreathingOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to try?.
        /// </summary>
        public static string BreathingQuestion {
            get {
                return ResourceManager.GetString("BreathingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available options:.
        /// </summary>
        public static string BreathingSelection {
            get {
                return ResourceManager.GetString("BreathingSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the buttons to select.
        /// </summary>
        public static string BreathingSelection1 {
            get {
                return ResourceManager.GetString("BreathingSelection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string BreathingStart {
            get {
                return ResourceManager.GetString("BreathingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string BreathingStop {
            get {
                return ResourceManager.GetString("BreathingStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you begin:.
        /// </summary>
        public static string BreathingTitle {
            get {
                return ResourceManager.GetString("BreathingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exercise will be approx. 1 minute long.
        /// </summary>
        public static string BreathingTitle1 {
            get {
                return ResourceManager.GetString("BreathingTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you are seated while doing this.
        /// </summary>
        public static string BreathingTitle2 {
            get {
                return ResourceManager.GetString("BreathingTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will see confirmation when this ends.
        /// </summary>
        public static string BreathingTitle3 {
            get {
                return ResourceManager.GetString("BreathingTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can press &quot;Start&quot; whenever ready.
        /// </summary>
        public static string BreathingTitle4 {
            get {
                return ResourceManager.GetString("BreathingTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Journal Entry.
        /// </summary>
        public static string CreateEntry {
            get {
                return ResourceManager.GetString("CreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold it for 1....
        /// </summary>
        public static string DeepBreathing1 {
            get {
                return ResourceManager.GetString("DeepBreathing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold it for 2....
        /// </summary>
        public static string DeepBreathing2 {
            get {
                return ResourceManager.GetString("DeepBreathing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold it for 3....
        /// </summary>
        public static string DeepBreathing3 {
            get {
                return ResourceManager.GetString("DeepBreathing3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold it for 4....
        /// </summary>
        public static string DeepBreathing4 {
            get {
                return ResourceManager.GetString("DeepBreathing4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold it for 5....
        /// </summary>
        public static string DeepBreathing5 {
            get {
                return ResourceManager.GetString("DeepBreathing5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhale slowly through nose....
        /// </summary>
        public static string DeepBreathingExhale {
            get {
                return ResourceManager.GetString("DeepBreathingExhale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only icons.
        /// </summary>
        public static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover over a button to get more info about how the program adapts!.
        /// </summary>
        public static string InfoTip {
            get {
                return ResourceManager.GetString("InfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program will open breathing exercises, have significantly bigger font, darker colors and icons where applicable.
        /// </summary>
        public static string Infotip_annoyed {
            get {
                return ResourceManager.GetString("Infotip_annoyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program will use calmer colors and an average sized font. UI will be simplified.
        /// </summary>
        public static string Infotip_calm {
            get {
                return ResourceManager.GetString("Infotip_calm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program will launch as normal.
        /// </summary>
        public static string Infotip_happy {
            get {
                return ResourceManager.GetString("Infotip_happy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program will offer breathing exercises before you begin, colors are darker, that don&apos;t cause mental strain.
        /// </summary>
        public static string Infotip_nerv {
            get {
                return ResourceManager.GetString("Infotip_nerv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a entry.
        /// </summary>
        public static string JournalButton {
            get {
                return ResourceManager.GetString("JournalButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a entry.
        /// </summary>
        public static string JournalButton1 {
            get {
                return ResourceManager.GetString("JournalButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Entries.
        /// </summary>
        public static string JournalTitle {
            get {
                return ResourceManager.GetString("JournalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Title.
        /// </summary>
        public static string JournalTitle1 {
            get {
                return ResourceManager.GetString("JournalTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Content.
        /// </summary>
        public static string JournalTitle2 {
            get {
                return ResourceManager.GetString("JournalTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Entry selected. Create one!.
        /// </summary>
        public static string JournalWatermark {
            get {
                return ResourceManager.GetString("JournalWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is empty. Maybe start with how you&apos;re feeling?.
        /// </summary>
        public static string JournalWatermark1 {
            get {
                return ResourceManager.GetString("JournalWatermark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages:.
        /// </summary>
        public static string LangSelect_title {
            get {
                return ResourceManager.GetString("LangSelect_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Mood Selector.
        /// </summary>
        public static string MoodButton {
            get {
                return ResourceManager.GetString("MoodButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annoyed.
        /// </summary>
        public static string MoodCard_annoyed {
            get {
                return ResourceManager.GetString("MoodCard_annoyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calm.
        /// </summary>
        public static string MoodCard_calm {
            get {
                return ResourceManager.GetString("MoodCard_calm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy.
        /// </summary>
        public static string MoodCard_happy {
            get {
                return ResourceManager.GetString("MoodCard_happy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nervous.
        /// </summary>
        public static string MoodCard_nerv {
            get {
                return ResourceManager.GetString("MoodCard_nerv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How are you feeling today?.
        /// </summary>
        public static string MoodGreeting {
            get {
                return ResourceManager.GetString("MoodGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mood selector.
        /// </summary>
        public static string MoodSelector_title {
            get {
                return ResourceManager.GetString("MoodSelector_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moody Pal - Happy mode.
        /// </summary>
        public static string MoodyMode {
            get {
                return ResourceManager.GetString("MoodyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moody Pal - Nervous mode.
        /// </summary>
        public static string MoodyMode1 {
            get {
                return ResourceManager.GetString("MoodyMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moody Pal - Annoyed mode.
        /// </summary>
        public static string MoodyMode2 {
            get {
                return ResourceManager.GetString("MoodyMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moody Pal - Calm mode.
        /// </summary>
        public static string MoodyMode3 {
            get {
                return ResourceManager.GetString("MoodyMode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading... Please wait.
        /// </summary>
        public static string StartupMessage {
            get {
                return ResourceManager.GetString("StartupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Timer.
        /// </summary>
        public static string TimerPause {
            get {
                return ResourceManager.GetString("TimerPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Timer.
        /// </summary>
        public static string TimerStart {
            get {
                return ResourceManager.GetString("TimerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Stop.
        /// </summary>
        public static string TimerStop {
            get {
                return ResourceManager.GetString("TimerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Session.
        /// </summary>
        public static string TimerTitle {
            get {
                return ResourceManager.GetString("TimerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ToDoAdd {
            get {
                return ResourceManager.GetString("ToDoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ToDoRemove {
            get {
                return ResourceManager.GetString("ToDoRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To-Do List.
        /// </summary>
        public static string ToDoTitle {
            get {
                return ResourceManager.GetString("ToDoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Item.
        /// </summary>
        public static string ToDoWatermark {
            get {
                return ResourceManager.GetString("ToDoWatermark", resourceCulture);
            }
        }
    }
}
